#' Generate config file \code{setup_inits.json} from simulated data
#'
#' Parses parameter object used to generate simulated data (generated by
#' [new_trueParams()]).
#'
#' @param params_used an object of \code{class} true_params (i.e. constructed
#'   via [new_trueParams()]) e.g. 'zeroParams' 'usedParams', see
#'   [get_zero_or_defaults()] and [generate_simulation_study()]
#' @inheritParams generate_yaml_model_defintion
#'
#' @return pure side-effect function that generates the \code{json}-file
#' @export
generate_setup_init_json <- function(params_used, pth_project) {
  pth_to_json <- file.path(pth_project, "model",
                           "model-definition",
                           "setup_inits.json")

  DD <- get_dimension(params_used, dim = "DD")

  list_json <- list()
  for(d in seq_len(DD)) {
    name_list_elem <- paste0("D", ifelse(d < 10, paste0(0, d), d))

    par_avail <- get_par_avail(params_used, num_d = d)

    par_to_list <- list()
    for (j in names(par_avail)) {
      par_to_list[[j]] <- par_to_list(par_avail[[j]], j, d)
    }
    list_json[[name_list_elem]] <- par_to_list
  }
  jsonlite::write_json(list_json, pth_to_json, digits = 8, pretty = TRUE)
}
par_to_list <- function(par_val, par_name, num_d) {
  if (par_name == "phi") {
    num_comp <- seq_len(length(par_val))
    lab <- paste0("phi_{", num_comp, ",", num_d,"}")
    var <- paste0(par_name, "_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "beta_z_lin") {
    num_comp <- seq_along(par_val)
    lab <- paste0("beta_{z", num_comp, ",", num_d, "}^{lin}")
    var <- paste0("Z_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "beta_u_lin") {
    if (is.null(nrow(par_val))) {
      num_comp <- 1
    } else {
      num_comp <- seq_len(nrow(par_val))
    }
    lab <- paste0("beta_{u", num_comp, ",", num_d, "}^{lin}")
    var <- paste0("U_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "vcm_u_lin") {
    lab <- paste0("vcm_beta_u{", num_d,"}")
    var <- paste0("buVCM", num_d)
    val <- par_val
  }
  if (par_name == "sig_sq") {
    lab <- paste0("sigma_{", num_d,"}")
    var <- paste0(par_name, num_d)
    val <- par_val
  }
  list(lab =  lab,
       var =  var,
       val =  val)
}
get_par_avail <- function(params_used, num_d) {
  check_pars <- c("phi", "beta_z_lin", "beta_u_lin", "sig_sq", "vcm_u_lin")
  id_avail  <- NULL
  par_avail <- vector("list", length(check_pars))
  names(par_avail) <- check_pars
  jj <- 1
  for (par_tmp in check_pars) {
    if(check_avail_param(params_used, par_tmp)) {
      if (par_tmp %in% c("phi", "sig_sq")) {tmp_n <- 1} else {tmp_n <- NULL}
      par_avail[[jj]] <- get_params(params_used,
                           n = tmp_n,
                           name_par = par_tmp,
                           DD = num_d)
      id_avail <- c(id_avail, jj)
    }
    jj <- jj + 1
  }
  par_avail[id_avail]
}
