#' Generate config file \code{setup_inits.json} from simulated data
#'
#' Parses parameter object used to generate simulated data (generated by
#' [new_trueParams()]).
#'
#' @param params_used an object of \code{class} true_params (i.e. constructed
#'   via [new_trueParams()]) e.g. 'zeroParams' 'usedParams', see
#'   [get_zero_or_defaults()] and [generate_simulation_study()]
#' @inheritParams generate_yaml_model_defintion
#'
#' @return pure side-effect function that generates the \code{json}-file
#' @export
generate_setup_init_json <- function(params_used, pth_project) {
  pth_to_json <- file.path(pth_project, "model",
                           "model-definition",
                           "setup_inits.json")
  browser()
  params_used$sig_sq <- params_used$sig_sq[, 1]
  DD <- length(params_used$sig_sq)

  list_json <- list()
  for(d in seq_len(DD)) {
    name_list_elem <- paste0("D", ifelse(d < 10, paste0(0, d), d))

    par_avail <- get_par_avail(params_used, num_d = d)
    par_avail_names <- names(par_avail)

    par_to_list <- list()
    for (j in par_avail_names) {
      par_to_list[[j]] <- par_to_list(par_avail[[j]], j, d)
    }
    list_json[[name_list_elem]] <- par_to_list
  }
  jsonlite::write_json(list_json, pth_to_json, digits = 8, pretty = TRUE)
}
par_to_list <- function(par_val, par_name, num_d) {
  if (par_name == "phi") {
    num_comp <- seq_len(length(par_val))
    lab <- paste0("phi_{", num_comp, ",", num_d,"}")
    var <- paste0(par_name, "_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "beta_z_lin") {
    num_comp <- seq_along(par_val)
    lab <- paste0("beta_{z", num_comp, ",", num_d, "}^{lin}")
    var <- paste0("Z_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "beta_u_lin") {
    if (is.null(nrow(par_val))) {
      num_comp <- 1
    } else {
      num_comp <- seq_len(nrow(par_val))
    }
    lab <- paste0("beta_{u", num_comp, ",", num_d, "}^{lin}")
    var <- paste0("U_", num_comp, "_", num_d)
    val <- par_val
  }
  if (par_name == "vcm_u_lin") {
    lab <- paste0("vcm_beta_u{", num_d,"}")
    var <- paste0("buVCM", num_d)
    val <- par_val
  }
  if (par_name == "sig_sq") {
    lab <- paste0("sigma_{", num_d,"}")
    var <- paste0(par_name, num_d)
    val <- par_val
  }
  list(lab =  lab,
       var =  var,
       val =  val)
}
get_par <- function(par_to_check, par_name, num_d) {
  if (par_name == "sig_sq") {
    if (!is.null(par_to_check)) return(par_to_check[num_d])
  } else if (par_name == "phi") {
    if (!is.null(par_to_check)) return(par_to_check[[num_d]][, 1])
  } else if (par_name %in% c("beta_z_lin", "beta_u_lin", "vcm_u_lin")) {
    if (!is.null(par_to_check)) return(par_to_check[[num_d]])
  } else {
    stop("Unknown parameter name.")
  }
}
get_par_avail <- function(params_used, num_d) {
  check_pars <- c("phi", "beta_z_lin", "beta_u_lin", "sig_sq", "vcm_u_lin")
  num_pars <- length(check_pars)
  id_avail  <- NULL
  par_avail <- vector("list", num_pars)
  for (j in seq_len(num_pars)) {
    if(isTRUE(!is.null((params_used[[check_pars[j]]])))) {
      par_avail[[j]] <- get_par(params_used[[check_pars[j]]],
                                check_pars[j], num_d)
      id_avail <- c(id_avail, j)
    }
  }
  par_avail <- par_avail[id_avail]
  names(par_avail) <- check_pars[id_avail]
  return(par_avail)
}
